[versions]
# Third-party
acra = "5.13.1"

# Testing
androidXTest = "1.7.0"

[libraries]
# AndroidX
androidx-appcompat-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-constraintlayout-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-core-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-core-core-remoteviews = { group = "androidx.core", name = "core-remoteviews", version = "1.1.0" }
androidx-core-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.2.0" }
androidx-exifinterface-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version = "1.4.2" }
androidx-palette-palette = { group = "androidx.palette", name = "palette", version = "1.0.0" }
androidx-preference-preference = { group = "androidx.preference", name = "preference", version = "1.2.1" }
com-google-android-material-material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
com-android-tools-desugar_jdk_libs = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }

# Third-party
com-journeyapps-zxing_android_embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version = "4.3.0" }
com-github-yalantis-ucrop = { group = "com.github.yalantis", name = "ucrop", version = "2.2.11" }
com-google-zxing-core = { group = "com.google.zxing", name = "core", version = "3.5.4" }
org-apache-commons-commons_csv = { group = "org.apache.commons", name = "commons-csv", version = "1.9.0" }
com-jaredrummler-colorpicker = { group = "com.jaredrummler", name = "colorpicker", version = "1.1.0" }
net-lingala-zip4j-zip4j = { group = "net.lingala.zip4j", name = "zip4j", version = "2.11.5" }
ch-acra-acra-mail = { group = "ch.acra", name = "acra-mail", version.ref = "acra" }
ch-acra-acra-dialog = { group = "ch.acra", name = "acra-dialog", version.ref = "acra" }

# Testing
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidXTest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidXTest" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-test-uiautomator-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version = "2.3.0" }
androidx-test-espresso-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
junit-junit = { group = "junit", name = "junit", version = "4.13.2" }
org-robolectric-robolectric = { group = "org.robolectric", name = "robolectric", version = "4.16" }

[plugins]
com-android-application = { id = "com.android.application", version = "8.13.2" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.21" }

[bundles]
acra = ["ch-acra-acra-mail", "ch-acra-acra-dialog"]
androidx-test = ["androidx-test-core", "androidx-test-runner"]
