name: Write contributors to file

on:
  workflow_dispatch:
  schedule:
    - cron: '3 4 * * 0'

permissions:
  contents: write
  pull-requests: write

jobs:
  contributors_to_file:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Write contributors to file
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v6
    - name: Update contributors
      id: update_contributors
      uses: TheLastProject/contributors-to-file-action@v3.2.0
      with:
        file_in_repo: app/src/main/res/raw/contributors.txt
        min_commit_count: 5
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8.0.0
      with:
        title: "Update contributors"
        commit-message: "Update contributors"
        branch-suffix: timestamp
