name: Gradle update
on:
  workflow_dispatch:
  schedule:
    - cron: '3 6 * * *'
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  gradle-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: obfusk/gradle-update-action@v2.0.0
      id: gradle-update
    - uses: gradle/wrapper-validation-action@v2
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6.0.3
      with:
        title: "Update Gradle to ${{ steps.gradle-update.outputs.version }}"
        commit-message: "Update Gradle to ${{ steps.gradle-update.outputs.version }}"
        branch-suffix: timestamp
